USE [master]
GO

/****** Object:  Database [FinancialInstitution]    Script Date: 5/14/2023 9:19:38 PM ******/
CREATE DATABASE [FinancialInstitution]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FinancialInstitution', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FinancialInstitution.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FinancialInstitution_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FinancialInstitution_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FinancialInstitution].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FinancialInstitution] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FinancialInstitution] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FinancialInstitution] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FinancialInstitution] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FinancialInstitution] SET ARITHABORT OFF 
GO

ALTER DATABASE [FinancialInstitution] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FinancialInstitution] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FinancialInstitution] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FinancialInstitution] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FinancialInstitution] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FinancialInstitution] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FinancialInstitution] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FinancialInstitution] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FinancialInstitution] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FinancialInstitution] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FinancialInstitution] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FinancialInstitution] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FinancialInstitution] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FinancialInstitution] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FinancialInstitution] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FinancialInstitution] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FinancialInstitution] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FinancialInstitution] SET RECOVERY FULL 
GO

ALTER DATABASE [FinancialInstitution] SET  MULTI_USER 
GO

ALTER DATABASE [FinancialInstitution] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FinancialInstitution] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FinancialInstitution] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FinancialInstitution] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FinancialInstitution] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FinancialInstitution] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FinancialInstitution] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FinancialInstitution] SET  READ_WRITE 
GO

