// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BedstedFinalProject.Models
{
    public partial class Account
    {
        public Account()
        {
            TransactionAccountIdgiverNavigations = new HashSet<Transactions>();
            TransactionAccountIdrecieverNavigations = new HashSet<Transactions>();
            Withdrawls = new HashSet<Withdrawl>();
        }

        public string AccountId { get; set; }
        public string UserId { get; set; }
        public decimal AccountBalance { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Transactions> TransactionAccountIdgiverNavigations { get; set; }
        public virtual ICollection<Transactions> TransactionAccountIdrecieverNavigations { get; set; }
        public virtual ICollection<Withdrawl> Withdrawls { get; set; }
    }
}