// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BedstedFinalProject.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Transactions = new HashSet<Transactions>();
        }

        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }

        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}