// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BedstedFinalProject.Models
{
    public partial class Transactions
    {
        public string TransactionId { get; set; }
        public string AccountIdgiver { get; set; }
        public string AccountIdreciever { get; set; }
        public string EmployeeId { get; set; }
        public decimal TransactionAmount { get; set; }

        public virtual Account AccountIdgiverNavigation { get; set; }
        public virtual Account AccountIdrecieverNavigation { get; set; }
        public virtual Employee Employee { get; set; }
    }
}