// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BedstedFinalProject.Models
{
    public partial class Users
    {
        public Users()
        {
            Accounts = new HashSet<Account>();
        }

        public string UserdId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }

        public virtual ICollection<Account> Accounts { get; set; }
    }
}