// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BedstedFinalProject.Models
{
    public partial class Withdrawl
    {
        public string WithdrawlId { get; set; }
        public string AccountId { get; set; }
        public decimal WithdrawlAmount { get; set; }

        public virtual Account Account { get; set; }
    }
}